# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Coffee Ratio' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Coffee Ratio
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
	'RCTImage',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  target 'Coffee Ratio UITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Coffee RatioTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
